`r opts_chunk$set(cache=TRUE)`
# Basic varying intercept multilevel model

$$y_{ij} = \alpha_i + \beta * x_{ij} + e_{ij}$$


# Import packages
```{r setup, message=FALSE}
rm(list=ls())
library(rjags)
library(coda)
library(lattice)
```


# Specify and export BUGS model
```{r}
modelstring <- "
model {
    # Model
    for (i in 1:N) {
        for (j in 1:J) {
            mu[i,j] <- alpha[i] + beta * (X[i,j] - x.bar);
            Y[i,j]   ~ dnorm(mu[i, j], tau.c)
        }
        alpha[i] ~ dnorm(alpha.mu, alpha.tau);
    }

    # Priors
    beta      ~ dnorm(0, 1.0E-4);
    alpha.mu  ~ dnorm(0, 1.0E-4);    
    tau.c     ~ dgamma(1.0E-3, 1.0E-3);
    alpha.tau ~ dgamma(1.0E-3, 1.0E-3);

    # Transformations
    alpha.sigma  <- 1.0/sqrt(alpha.tau);
    sigma.c    <- 1.0/sqrt(tau.c);
    x.bar    <- mean(X[,]);
    alpha0   <- alpha.mu - beta*x.bar;
}
"
writeLines(modelstring, "model.txt")
```

# Generate Data
```{r}
set.seed(4444)
Alpha.Mu <- 2
Alpha.Sigma <- 2
Beta <- 1
Sigma <- 1
J <- 10
N <- 15

Data <- expand.grid(id.i=seq(1:N), id.j=seq(1,J))
Data$latex x <- rnorm(nrow(Data), mean=5, sd=1)
Alpha <- rnorm(N, Alpha.Mu, Alpha.Sigma)
Data$latex alpha <- Alpha[Data$id.i]
Data$latex error <- rnorm(nrow(Data), 0, Sigma)
Data$latex yhat <- Data$latex alpha + Beta * Data$x
Data$latex y <- Data$latex yhat + Data$error


# Convert data to input format required by JAGS

Data.wide.x <- reshape(Data[,c('id.i', 'id.j', 'x')], idvar='id.i', timevar='id.j', direction='wide')
Data.wide.x$id.i <- NULL
Data.wide.y <- reshape(Data[,c('id.i', 'id.j', 'y')], idvar='id.i', timevar='id.j', direction='wide')
Data.wide.y$id.i <- NULL

jagsdata <- list(X=as.matrix(Data.wide.x), Y=as.matrix(Data.wide.y), N=N, J=J)
```

# Traditional analysis
```{r}
xyplot(y~x|factor(id.i), Data)
lm(y~x*factor(id.i), Data)

fits <- NULL
for (i in unique(Data$id.i)) {
    fits[[i]] <- lm(y~x, Data[Data$id.i == i, ]) 
    names(fits)[i] <- paste(i)
}

coefs <- sapply(fits, coef)
rownames(coefs) <- c("alpha", "beta")
summary(coefs['alpha', ]); sd(coefs['alpha', ])
summary(coefs['beta', ])
```

# Bayesian analysis
```{r}
mod1 <- jags.model("model.txt", data=jagsdata, n.chains=4, n.adapt=1000)
update(mod1, 1000) # burn in

# monitor
mod1.samples <- coda.samples(model=mod1,
                             variable.names=c('alpha.mu', 'alpha.sigma', 
                                              'beta',  'alpha0',
                                              'sigma.c'),
                             n.iter=1000)                  

# Model summary and diagnostics
plot(mod1.samples) # plot trace and posterior density for each parameter
summary(mod1.samples) # print descriptive statistics of posterior densities for parameters
```
