

$latex y_i$ is drawn from a categorical distribution with three categories.

$$latex p(y) = \pi_1^{[y=1]}, \pi_2^{[y=2]}, \pi_3^{[y=3]}$$
$$latex \pi = \beta$$
$$latex \beta_1 \sim Unif(0, 1)$$
$$latex \beta_2 \sim Unif(0, 1 - \beta_1)$$
$$latex \beta_3 \sim Unif(0, 1 - \beta_1 - \beta_2)$$


# Setup
```{r setup, message=FALSE}
rm(list=ls())
require(rjags)
require(coda)
```

# Generate data
```{r}
N <- 100
y <- sample(1:3, replace=TRUE, size=N, prob=c(.2, .3, .5))
Data <- list(y=y)
```


# Specify JAGS script
```{r}
jags.script <- "
model{
    # likelihood
    for( i in 1:length(y)) {
        y[i] ~ dcat(pi)
    }

    # priors
    Beta[1] ~ dunif(0, 1)
    Beta[2] ~ dunif(0, 1-Beta[1])
    Beta[3] <- 1 - Beta[1] - Beta[2]
    pi <- Beta
}
"
```


# Perform Bayesian analysis using JAGS
```{r}
jags.fit <- jags.model(textConnection(jags.script), data=Data, n.chains=4, n.adapt=1000)

update(jags.fit, n.iter=1000) # burnin

jags.samples <- coda.samples(model=jags.fit,
                             variable.names=c('pi'),
                             n.iter=1000)
plot(jags.samples) # plot trace and posterior density for each parameter
summary(jags.samples) # print descriptive statistics of posterior densities for parameters
```